window.INITIAL_FIELD_CALLS = [
    {
        "id":  1,
        "udise":  "33190400501",
        "district":  "Nagapattinam",
        "block":  "Keezhaiyur",
        "schoolName":  "PUMS VILUNTHAMAVADI WEST",
        "issue":  "SYSTEM 5,8 N/W NOT CONNECTED",
        "category":  "HELPLINE TICKET",
        "aiName":  "",
        "contactNo": "984011001",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  269,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  2,
        "udise":  "33190102201",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "PUMS THERKKU POIGAINALLUR",
        "issue":  "I/O BOX DAMAGED",
        "category":  "HELPLINE TICKET",
        "aiName":  "",
        "contactNo": "984011002",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  223,
        "status":  "Completed",
        "visitedBy":  ""
    },
    {
        "id":  3,
        "udise":  "33190300901",
        "district":  "Nagapattinam",
        "block":  "Kelvelur",
        "schoolName":  "PUMS KURUMANANGUDI",
        "issue":  "IO BOX PROBLEM",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011003",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  219,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  4,
        "udise":  "33190301001",
        "district":  "Nagapattinam",
        "block":  "Kelvelur",
        "schoolName":  "PUMS ATHIPULIYUR",
        "issue":  "IO box problem",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011004",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  219,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  5,
        "udise":  "33190202401",
        "district":  "Nagapattinam",
        "block":  "Thirumarugal",
        "schoolName":  "PUMS ATHALAIYUR",
        "issue":  "D-Link to system lan cable not connected",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "Ranjitha",
        "contactNo": "984011005",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  216,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  6,
        "udise":  "33190503301",
        "district":  "Nagapattinam",
        "block":  "Thalainayar",
        "schoolName":  "GHSS VELLAPALLAM",
        "issue":  "UNABLE TO CONNECT INTERNET",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011006",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  215,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  7,
        "udise":  "33190301901",
        "district":  "Nagapattinam",
        "block":  "Kelvelur",
        "schoolName":  "PUMS VADAKKALATHUR",
        "issue":  "1 SYSTEM I/O PORT ISSUE",
        "category":  "HELPLINE TICKET",
        "aiName":  "",
        "contactNo": "984011007",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  214,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  8,
        "udise":  "33190500801",
        "district":  "Nagapattinam",
        "block":  "Thalainayar",
        "schoolName":  "PUMS MARACHERY",
        "issue":  "6TH SYSTEM I/O BOX NOT WORKING",
        "category":  "HELPLINE TICKET",
        "aiName":  "",
        "contactNo": "984011008",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  194,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  9,
        "udise":  "33190303103",
        "district":  "Nagapattinam",
        "block":  "Kelvelur",
        "schoolName":  "PUMS KERALANTHAN",
        "issue":  "Cpu and monitor current not supply",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011009",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  193,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  10,
        "udise":  "33190601004",
        "district":  "Nagapattinam",
        "block":  "Vedaranyam",
        "schoolName":  "PUMS THIRD STREET, VEDARANIYAM",
        "issue":  "Cpu to I/O port not working",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011010",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  192,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  11,
        "udise":  "33190602401",
        "district":  "Nagapattinam",
        "block":  "Vedaranyam",
        "schoolName":  "PUMS,VOIMEDU WEST",
        "issue":  "CPU to input output internet port not working",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011011",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  189,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  12,
        "udise":  "33190602104",
        "district":  "Nagapattinam",
        "block":  "Vedaranyam",
        "schoolName":  "PUMS THANIKOTTAGAM SOUTH",
        "issue":  "CPU Input output internet port not working",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011012",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  189,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  13,
        "udise":  "33190301601",
        "district":  "Nagapattinam",
        "block":  "Kelvelur",
        "schoolName":  "PUMS KUTHUR",
        "issue":  "One system has no internet connection",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011013",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  174,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  14,
        "udise":  "33190202701",
        "district":  "Nagapattinam",
        "block":  "Thirumarugal",
        "schoolName":  "PUMS-THIRUCHENKATTANGUDI",
        "issue":  "HDMI CABLE DEMAGED",
        "category":  "HELPLINE TICKET",
        "aiName":  "",
        "contactNo": "984011014",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  174,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  15,
        "udise":  "33190202301",
        "district":  "Nagapattinam",
        "block":  "Thirumarugal",
        "schoolName":  "PUMS-VADAKARAI",
        "issue":  "D-Link not connected",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "Parimala Devi",
        "contactNo": "984011015",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  173,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  16,
        "udise":  "33190500701",
        "district":  "Nagapattinam",
        "block":  "Thalainayar",
        "schoolName":  "PUMS THIRUVIDAIMARUTHUR",
        "issue":  "UPS IO BOX",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011016",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  156,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  17,
        "udise":  "33190203901",
        "district":  "Nagapattinam",
        "block":  "Thirumarugal",
        "schoolName":  "PUMS-KANGALANCHERY",
        "issue":  "WEB CAMERA NOT RECEIVED",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "Shanthini",
        "contactNo": "984011017",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  154,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  18,
        "udise":  "33190200902",
        "district":  "Nagapattinam",
        "block":  "Thirumarugal",
        "schoolName":  "PUPS-GOTHANDARAJAPURAM",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011018",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  19,
        "udise":  "33190200102",
        "district":  "Nagapattinam",
        "block":  "Thirumarugal",
        "schoolName":  "PUPS-GANAPATHIPURAM",
        "issue":  "UPS LAN cable not received and  Internet connection not available",
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011019",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  20,
        "udise":  "33190102601",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "PUPS ALANGUDI",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011020",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  21,
        "udise":  "33190102303",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "GHS,VADAVOOR",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011021",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  22,
        "udise":  "33190101801",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "PUPS PUDUCHERY",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011022",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  23,
        "udise":  "33190203602",
        "district":  "Nagapattinam",
        "block":  "Thirumarugal",
        "schoolName":  "PUPS - VICHUR",
        "issue":  "UPS LAN cable not received",
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011023",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  24,
        "udise":  "33190400901",
        "district":  "Nagapattinam",
        "block":  "Keezhaiyur",
        "schoolName":  "PUMS THATHANTHIRUVASAL",
        "issue":  "TWO SYSTEM TABLE NOT ASSEMBLED(SCREW NOT AVAILABLE)",
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011024",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  25,
        "udise":  "33190401005",
        "district":  "Nagapattinam",
        "block":  "Keezhaiyur",
        "schoolName":  "PUPS SALLIKULAM",
        "issue":  "NO POWER CONNECTION IN 9U RACK,UPS NOT WORKING,ELECTRICAL WORK WAS INCOMPLETED.",
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011025",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  26,
        "udise":  "33190401301",
        "district":  "Nagapattinam",
        "block":  "Keezhaiyur",
        "schoolName":  "GHSS PALAKKURICHI",
        "issue":  "Ups not received.",
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011026",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  27,
        "udise":  "33190101502",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "PUPS PERIYANARIYANGUDI",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011027",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  28,
        "udise":  "33190501302",
        "district":  "Nagapattinam",
        "block":  "Thalainayar",
        "schoolName":  "PUPS AYYOR",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011028",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  29,
        "udise":  "33190503304",
        "district":  "Nagapattinam",
        "block":  "Thalainayar",
        "schoolName":  "PUPS VANAVANMAHADEVI WEST",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011029",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  30,
        "udise":  "33190503403",
        "district":  "Nagapattinam",
        "block":  "Thalainayar",
        "schoolName":  "PUPS ULAGANATHANKADU",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011030",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  31,
        "udise":  "33190304301",
        "district":  "Nagapattinam",
        "block":  "Kelvelur",
        "schoolName":  "PUPS THERKUPANAIYUR",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011031",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  32,
        "udise":  "33190101405",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "PUPS AKKARAIPETTAI",
        "issue":  "Web camere and computer to smartboard connected wire not receive in this school",
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011032",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  33,
        "udise":  "33190103151",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "MMS KALLUKARA STREET.",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011033",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  34,
        "udise":  "33190604302",
        "district":  "Nagapattinam",
        "block":  "Vedaranyam",
        "schoolName":  "PUMS SEMBAGARAYANALLUR NORTH",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011034",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  35,
        "udise":  "33190603802",
        "district":  "Nagapattinam",
        "block":  "Vedaranyam",
        "schoolName":  "PUMS,MOOLAKKARAI",
        "issue":  "Projector mountkit not received projector installation pending also invertor not connected to computer system",
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011035",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  36,
        "udise":  "33190603001",
        "district":  "Nagapattinam",
        "block":  "Vedaranyam",
        "schoolName":  "PUMS, AYAKKARANPULAM 2",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011036",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  37,
        "udise":  "33190602101",
        "district":  "Nagapattinam",
        "block":  "Vedaranyam",
        "schoolName":  "PUMS, VELLIKIDANKU",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011037",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  38,
        "udise":  "33190601202",
        "district":  "Nagapattinam",
        "block":  "Vedaranyam",
        "schoolName":  "PUMS,THOPPUTHURAI(MUSILIM)",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011038",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  39,
        "udise":  "33190602901",
        "district":  "Nagapattinam",
        "block":  "Vedaranyam",
        "schoolName":  "PUPS PANCHANATHIKULAM EAST SECOND WARD",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011039",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  40,
        "udise":  "33190302601",
        "district":  "Nagapattinam",
        "block":  "Kelvelur",
        "schoolName":  "PUMS VANDALUR",
        "issue":  "Two computers do not have internet.",
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011040",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  41,
        "udise":  "33190602601",
        "district":  "Nagapattinam",
        "block":  "Vedaranyam",
        "schoolName":  "PUPS, PANCHANATHIKULAM WEST",
        "issue":  "Electric circuit issue.",
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011041",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  42,
        "udise":  "33190103005",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "MMS MIYAH STREET NAGORE",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011042",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  43,
        "udise":  "33190101901",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "PUMS VERGUDI",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011043",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  44,
        "udise":  "33190101404",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "PUMS KEECHANKUPPAM",
        "issue":  "Ups problem and projector screen not closing issue",
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011044",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  45,
        "udise":  "33190100502",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "PUPS PALAKKADU",
        "issue":  "Computer not connecting internet in this school.",
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011045",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  46,
        "udise":  "33190602703",
        "district":  "Nagapattinam",
        "block":  "Vedaranyam",
        "schoolName":  "GHS MARUTHUR SOUTH",
        "issue":  [
                      [

                      ]
                  ],
        "category":  "GOOGLE FORM - AI",
        "aiName":  "",
        "contactNo": "984011046",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  139,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  47,
        "udise":  "33190102401",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "PUMS KURICHI",
        "issue":  "LAN cable not working",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011047",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  137,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  48,
        "udise":  "33190502401",
        "district":  "Nagapattinam",
        "block":  "Thalainayar",
        "schoolName":  "PUMS PRINJUMOOLAI",
        "issue":  "network problem",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011048",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  133,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  49,
        "udise":  "33190203302",
        "district":  "Nagapattinam",
        "block":  "Thirumarugal",
        "schoolName":  "PUMS PORAKUDI",
        "issue":  "CPU I/O Point",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "Semmalar",
        "contactNo": "984011049",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  129,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  50,
        "udise":  "33190103139",
        "district":  "Nagapattinam",
        "block":  "Nagapattinam",
        "schoolName":  "MPS KOTTAIMEDU STREET",
        "issue":  "1.MERAKI ROUTER 2.D-LINK 8PORT SWITCH 3.IP CAMERA 4.WEBCAMERA NOT DELIVERED",
        "category":  "TICKETING TOOL TICKET",
        "aiName":  "",
        "contactNo": "984011050",
        "zone611001":  "YES",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  116,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  51,
        "udise":  "33190204101",
        "district":  "Nagapattinam",
        "block":  "Thirumarugal",
        "schoolName":  "PUPS - VIRKUDI",
        "issue":  "power supply issue",
        "category":  "Ticketing Tool",
        "aiName":  "Shanthini",
        "contactNo": "984011051",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  1,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  52,
        "udise":  "33190204001",
        "district":  "Nagapattinam",
        "block":  "Thirumarugal",
        "schoolName":  "PUPS - VAZKUDI",
        "issue":  "DUE TO THE IP CAMERA BEING POSITIONED DOWNWARD,THE CLASSROOM IS NOT VISIBLE.ONLY THE FLOOR TILES CAN BESEEN.",
        "category":  "KS SMART",
        "aiName":  "Shanthini",
        "contactNo": "984011052",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  1,
        "status":  "Not Started",
        "visitedBy":  ""
    },
    {
        "id":  53,
        "udise":  "33190203801",
        "district":  "Nagapattinam",
        "block":  "Thirumarugal",
        "schoolName":  "PUPS RARANTHIMANGALAM",
        "issue":  "DUE TO THE IP CAMERA BEING POSITIONED DOWNWARD,THE CLASSROOM IS NOT VISIBLE.ONLY THE FLOOR TILES CAN BESEEN.",
        "category":  "KS SMART",
        "aiName":  "Shanthini",
        "contactNo": "984011053",
        "zone611001":  "NO",
        "ticketRaisedOn":  "2026-08-08",
        "ageDays":  1,
        "status":  "Not Started",
        "visitedBy":  ""
    }
];
